[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["rm -rf pnpm-lock.yaml", "pnpm install --no-frozen-lockfile --config.ignore-scripts=false"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"